### ISSUE TITLE
factor out RSign as its own repository

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/RChain-Status#4]

**Comment by JoshOrndorff** [comment]
I think you should be upstream on that one. I'll fork to make suggestions.

**Comment by dckc** [comment]
untested: https://github.com/dckc/RSign c9fad6d

**Comment by dckc** [comment]
OK, so it's now lightly tested (6298ceb). But... the Rchain-Status app imports from `sigui` in a couple places:

```
~/projects/Rchain-Status$ grep sigui *.js *.html
page.js:} from './sigui/messageBus.js';
index.html:<script src="sigui/lib/protobuf.min.js"></script>
```

Maybe those are just dead code.

Here's hoping for time to look more closely...

**Comment by JoshOrndorff** [comment]
https://github.com/rchain-community/RSign
