### ISSUE TITLE
publish video of setting up RSign

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/Rchain-Status#5]
I helped Seth set it up and he agreed to let me record the Zoom session.

**Comment by JoshOrndorff** [comment]
Oh, that's great! We could link it in the README. You have a youtube account?

**Comment by dckc** [comment]
No youtube account... I can share it via google drive or dropbox and then
we can leave it there or put it other places.

**Comment by dckc** [comment]
unedited: [zoom_0.mp4](https://www.dropbox.com/home/Public/2018-09-06%2011.16.17%20Dan%20Connolly's%20Zoom%20Meeting%20671786621?preview=zoom_0.mp4)

**Comment by dckc** [comment]
for follow-up, see https://github.com/dckc/RSign/issues/15
